bitextor: /home/hieu/permanent/software/bitextor
  #"domains:  ["www.adfasdffdsaasdf.com"],

  #"langstat: /home/hieu/permanent/software/langstat/1k.gz
  #"langstatThreshold: 10,
    
langstat: /home/hieu/permanent/langstat/langstats.all.gz
langstatThreshold: 5000

langstatExcludeDomains: /home/hieu/permanent/software/bitextor/snakemake/exclude-domains
temp: /mnt/tmp
permanentDir: /home/hieu/permanent/so-en.large
transientDir: /home/hieu/transient/so-en.large
lang1: so
lang2: en
  #"dic: /home/hieu/permanent/software/bitextor-data/dics/en-fr.dic
hunalignThreshold: 0
maxlines: 5
crawlTimeLimit: 43200s
tmx: true
nmt: true
smt: true
httrack: true

elrc: true
crawlerNumThreads: 2
crawlTld: false
  #"bicleanerThreshold: 0.7
bicleaner: /home/hieu/transient/so-en.large/bicleaner/en-so.yaml
bicleanerCorpusTrainingPrefix: ["/home/hieu/permanent/data/so-en/material-only/train.txt"]
documentAligner: SMT
alignerCmd: marek-smt
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.2

marianDir: /home/hieu/permanent/software/marian-dev
subwordNmtDir: /home/hieu/permanent/software/subword-nmt
mosesDir: /home/hieu/permanent/software/mosesdecoder

marianArgs: [" --optimizer-delay 1 --mini-batch-fit --mini-batch 1000 --maxi-batch 1000",
                 " --overwrite --keep-best --valid-metrics perplexity",
                 " --valid-log valid.log --log train.log",
                 " --dropout-rnn 0.2 --dropout-src 0.2 --dropout-trg 0.2 ",
                 "--cost-type ce-mean-words --layer-normalization --exponential-smoothing --tied-embeddings",
                 "--valid-metrics bleu"
                ]
#marianModelFile: model.npz.decoder.yml
#marianModelFile: model.npz.best-perplexity.npz.decoder.yml
marianModelFile: model.npz.best-bleu.npz.decoder.yml

initCorpusTrainPrefix: ["/home/hieu/permanent/data/so-en/material-only/train.txt"]
initCorpusDevPrefix: ["/home/hieu/permanent/data/so-en/material-only/dev.txt"]
initCorpusTestPrefix: ["/home/hieu/permanent/data/so-en/material-only/dev.txt",
                       "/home/hieu/permanent/data/so-en/material-only/test.txt"]

gpuId: 0
LANG1Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l so
LANG2Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l en
LANG2Detokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/detokenizer.perl -l en
LANG1SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -q -b -l so
LANG2SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -q -b -l en

nmtVocabSize: 30000

mgiza: /home/hieu/permanent/software/mgiza
