bitextor: /home/hieu/permanent/software/bitextor
  #"domains:  ["www.adfasdffdsaasdf.com"],

  #"langstat: /home/hieu/permanent/software/langstat/1k.gz
  #"langstatThreshold: 10,
    
langstat: /home/s0565741/workspace/experiment/issues/paracrawl/langstat/langstats.all.gz
langstatThreshold: 5000

#linkedHosts: []
#linkedHostsAction: remove

langstatExcludeStrings: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/langstat-exclude-strings
excludeHostsFile: /home/s0565741/workspace/github/paracrawl/bitextor.malign/snakemake/exclude-hosts

temp: /raid0/tmp
permanentDir: /home/s0565741/workspace/experiment/paracrawl/v3/hu-en/permanent
transientDir: /home/s0565741/workspace/experiment/paracrawl/v3/hu-en/transient
lang1: hu
lang2: en
  #"dic: /home/hieu/permanent/software/bitextor-data/dics/en-fr.dic
hunalignThreshold: 0
maxlines: 5
crawlTimeLimit: 43200s
tmx: true
nmt: true
smt: true
httrack: true

elrc: true
crawlerNumThreads: 2
crawlTld: false
  #"bicleanerThreshold: 0.7
bicleaner: /home/hieu/transient/hu-en/bicleaner/en-hu.yaml
bicleanerCorpusTrainingPrefix: ["/home/hieu/permanent/data/hu-en/train/Books.en-hu"]
documentAligner: SMT
alignerCmd: marek-smt
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.2

marianDir: /home/hieu/permanent/software/marian-dev
subwordNmtDir: /home/hieu/permanent/software/subword-nmt
mosesDir: /home/hieu/permanent/software/mosesdecoder

marianArgs: [" --optimizer-delay 1 --mini-batch-fit --mini-batch 1000 --maxi-batch 1000",
                 " --overwrite --keep-best --valid-metrics perplexity",
                 " --valid-log valid.log --log train.log",
                 " --dropout-rnn 0.2 --dropout-src 0.2 --dropout-trg 0.2 ",
                 "--cost-type ce-mean-words --layer-normalization --exponential-smoothing --tied-embeddings",
                 "--valid-metrics bleu"
                ]
#marianModelFile: model.npz.decoder.yml
#marianModelFile: model.npz.best-perplexity.npz.decoder.yml
marianModelFile: model.npz.best-bleu.npz.decoder.yml

initCorpusTrainPrefix: ["/home/hieu/permanent/data/hu-en/train/Books.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/DGT.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/ECB.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/EMEA.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/EUbookshop.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/EUconst.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/Europarl.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/GNOME.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/GlobalVoices.en-hu.train",
                        "/home/hieu/permanent/data/hu-en/train/JRC-Acquis.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/OpenSubtitles2018.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/PHP.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/Tatoeba.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/Ubuntu.en-hu",
                        "/home/hieu/permanent/data/hu-en/train/Wikipedia.en-hu"
                       ]
initCorpusDevPrefix: ["/home/hieu/permanent/data/hu-en/dev/GlobalVoices.en-hu.dev"]
initCorpusTestPrefix: ["/home/hieu/permanent/data/hu-en/dev/GlobalVoices.en-hu.dev",
                       "/home/hieu/permanent/data/hu-en/test/GlobalVoices.en-hu.test"]

gpuId: 0
LANG1Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l hu
LANG2Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l en
LANG2Detokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/detokenizer.perl -l en
LANG1SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -l hu
LANG2SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -l en

nmtVocabSize: 30000

mgiza: /home/hieu/permanent/software/mgiza
