bitextor: /home/hieu/workspace/github/paracrawl/bitextor.malign
hosts: ["www.adfasdffdsaasdf.com"]
#hostPath: /home/hieu/permanent/data/hosts/hosts.fr.3.gz

  #"langstat: /home/hieu/permanent/software/langstat/1k.gz
  #"langstatThreshold":10,
    
  #"langstat: /home/hieu/permanent/software/langstat/langstats.all.gz
  #"langstatThreshold":50000000,
#linkedHosts: ["/home/hieu/permanent/other-en"]
#linkedHostsAction: link

langstatExcludeStrings: /home/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/langstat-exclude-strings
temp: /tmp
permanentDir: /home/hieu/workspace/experiment/issues/paracrawl/workspace/fr-en.tiny/permanent
transientDir: /home/hieu/workspace/experiment/issues/paracrawl/workspace/fr-en.tiny/transient
lang1: fr
lang2: en
dic: /home/hieu/permanent/software/bitextor-data/dics/en-fr.dic
hunalignThreshold: 0
maxlines: 5

###### BOILERPIPE CLEANING #####
#If enabled, boilerpipe is not used
boilerpipeCleaning: true

crawlTimeLimit: 60s
crawlPageLimit: 100000
  #"crawlTimeLimit: 900s
  #"crawlTimeLimit: 60m

tmx: true
  #"nmt: true,
  #"smt: true,
httrack: true

elrc: true
crawlerNumThreads: 2
crawlTld: false
  #"bicleanerThreshold: 0.7,
  #"bicleaner: /home/hieu/permanent/software/bitextor-data/bicleaner/en-fr
documentAligner: SMT
alignerCmd: marek-smt
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.1

marianDir: /home/hieu/workspace/github/marian-dev
subwordNmtDir: /home/hieu/workspace/github/subword-nmt
mosesDir: /home/hieu/workspace/github/mosesdecoder

marianArgs: [" --optimizer-delay 1 --mini-batch-fit --mini-batch 1000 --maxi-batch 1000",
                 " --overwrite --keep-best --valid-metrics perplexity",
                 " --valid-log valid.log --log train.log",
                 " --dropout-rnn 0.2 --dropout-src 0.2 --dropout-trg 0.2 ",
                 "--cost-type ce-mean-words --layer-normalization --exponential-smoothing --tied-embeddings",
                 "--valid-metrics bleu"
                ]
#marianModelFile: model.npz.decoder.yml
#marianModelFile: model.npz.best-perplexity.npz.decoder.yml
marianModelFile: model.npz.best-bleu.npz.decoder.yml

initCorpusTrainPrefix: ["/home/hieu/workspace/experiment/issues/paracrawl/fr-en/train/1k/europarl-v7.fr-en"]
initCorpusDevPrefix: ["/home/hieu/workspace/experiment/issues/paracrawl/fr-en/wmt07/dev/dev2006"]
initCorpusTestPrefix: ["/home/hieu/workspace/experiment/issues/paracrawl/fr-en/wmt07/dev/dev2006",
                    "/home/hieu/workspace/experiment/issues/paracrawl/fr-en/wmt07/dev/nc-dev2007",
                    ]

gpuId: 0
LANG1Tokenizer: /home/hieu/workspace/github/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l fr
LANG2Tokenizer: /home/hieu/workspace/github/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l en
LANG2Detokenizer: /home/hieu/workspace/github/mosesdecoder/scripts/tokenizer/detokenizer.perl -l en

LANG1SentenceSplitter: /home/hieu/workspace/github/mosesdecoder/scripts/ems/support/split-sentences.perl -b -l fr
LANG2SentenceSplitter: /home/hieu/workspace/github/mosesdecoder/scripts/ems/support/split-sentences.perl -b -l en

nmtVocabSize: 30000

mgiza: /home/hieu/workspace/github/mgiza


