bitextor: /home/mespla/Projects/bitextor-malign
hosts: ['www.adfasdffdsaasdf.com']
#documentAligner: DIC
documentAligner: externalMT
temp: /tmp/transient
httrack: true
permanentDir: /tmp/persistent/bitextor-output
transientDir: /tmp/transient
nmt: false
smt: false
lang1: fr
lang2: en
dic: /tmp/persistent/en-fr.dic
hunalignThreshold: 0
maxlines: 5
elrc: true
crawlerNumThreads: 2
crawlTld: false
bicleaner: /home/mespla/fr-en/training.en-fr.yaml
mosesDir: /home/mespla/Programari/mosesdecoder-RELEASE-4.0
tmx: true
initCorpusTrainPrefix: [/tmp/persistent/EUconst.en-fr]
bicleanerCorpusTrainingPrefix: [/tmp/persistent/RF.en-fr]
bicleanerThreshold: 0.5
LANG1Tokenizer: /home/mespla/Projects/bitextor-malign/preprocess/moses/tokenizer/tokenizer.perl -a -b -q -l fr
LANG2Tokenizer: /home/mespla/Projects/bitextor-malign/preprocess/moses/tokenizer/tokenizer.perl -a -b -q -l en
LANG1SentenceSplitter: /home/mespla/Projects/bitextor-malign/preprocess/moses/ems/support/split-sentences.perl -b -l fr
LANG2SentenceSplitter: /home/mespla/Projects/bitextor-malign/preprocess/moses/ems/support/split-sentences.perl -b -l en
deduped: false
alignerCmd: ~/Projects/bitextor-malign/snakemake/example/translate.miquel.sh
#boilerpipeCleaning: True
bleualign: true
